name-template: "v$NEXT_PATCH"
tag-template: "v$NEXT_PATCH"
categories:
  - title: "ğŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ğŸ› Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "ğŸ› ï¸ Maintenance"
    labels:
      - "chore"
      - "docs"
      - "refactor"
change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
change-title-escapes: "\<\>"
template: |
  ## What's Changed

  $CHANGES

  ---
  **Full Changelog:** [$PREVIOUS_TAG...$NEW_TAG](https://github.com/OWNER/REPO/compare/$PREVIOUS_TAG...$NEW_TAG)
